name: PHP Style

on: [push, workflow_dispatch]

jobs:
    php-cs-fixer:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - name: PHP-CS-Fixer
              uses: docker://oskarstark/php-cs-fixer-ga:2.19.0
              with:
                  args: --config=.php_cs.dist --allow-risky yes

            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Apply php-cs-fixer changes
                  
            - uses: actions/checkout@master
            - name: Microsoft Teams Notification
              uses: skitionek/notify-microsoft-teams@master
              if: always()
              with:
                webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
                needs: ${{ toJson(needs) }}
                job: ${{ toJson(job) }}
                steps: ${{ toJson(steps) }}
